[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.17.0"
  NEXT_PUBLIC_SITE_URL = "https://swiftlogistics.netlify.app"

[[plugins]]
  package = "@netlify/plugin-nextjs" 