[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20.10.0"
  NEXT_PUBLIC_SITE_URL = "https://swiftlogisticsng.com"

[[plugins]]
  package = "@netlify/plugin-nextjs" 